### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Syno0** [agerwick/RT28XX-RT539X-Linux-driver#2]
I try your solution and I restart my computer and now my Ubuntu 14.04 totally crash when I start any application (Mozilla, Search, ...).

I have to pull the power button to shutdown ...

Any solution ?

**Comment by agerwick** [comment]
Unfortunately I no longer have a computer with this network adapter, so I have no way to test at this time. Also, with this little information, I wouldn't be able to test anything anyway. I tested it on Ubuntu 14.04 a couple of years ago and it worked then, so I posted it here so other people could use the same solution, or use it as a basis for a solution if it doesn't work out of the box. If you do find a solution, feel free to post the it here, fork this repository and modify it, submit a patch or whatever you think can help other people with the same issue.

That said, have you ruled out your network adapter being defective?
Also, are you sure you have this exact network adapter?

**Comment by Syno0** [comment]
Thank you for the answer, yes I have a rt5390 and I try your solution because my wifi connection is very slow on Ubuntu and I don't understand why ( I try a lot of differents things without found any solution .. )

I don't really understand how to use the update-driver-after-kernel-upgrade file, can you explain it again plz ? Maybe it can fix the crash.

**Comment by agerwick** [comment]
The main problem with the RT539X is that there are no fully working open source drivers, or at least there weren't when I made this a couple of years ago. The proprietary driver that this solution uses is not ideal, but I had the choice between a non-ideal solution and no wireless...
The biggest issue, apart from the licensing and the fact we have no way to fix any issues with the driver, is that every time the Linux kernel is updated, this driver (or part of the driver) needs to be recompiled for that kernel. That's what the update-driver-after-kernel-upgrade script does.
The symptoms for needing to run that script however, are not the same as you are experiencing. If I remember correctly, after booting to a new kernel, the wireless card would simply not be detected, as if you had no WIFI at all. I never had any issues with crashes. The only reason for ever needing to run the script is after a kernel update - it solves no other problems. So if you've installed this driver (or run that script) and you haven't updated the Linux kernel, then running the script will only waste your time.
I need to point out, I am in no way an expert on these things. If I were, I might have been able to find a way not needing to run that script. I was setting up a laptop for a friend and found the existing ways to implement this solution too difficult for non-developers, so I made this by trial and error. I figured that other people may benefit from it as well, so I published it here. Of course I only ever tested it on that one computer, and I think I used it again another time on a different computer, but that sums up my entire experience with it :)

By the way, which kernel version do you use? It's a shot in the dark, but you could try using an older kernel. The one I used was 3.8.something.

**Comment by steaksauce-** [comment]
I too have this issue.

While not a working solution to get this driver to work, I was able to get things back to normal:

Boot to GRUB (hold shift during boot)
Select Advanced Options
Select Recovery Mode
After booting to a menu, select the root console option
'mount -o remount,rw /'    This will remount the system in read/write mode.
vim /etc/modules (or use nano). Comment out the line that you added to install.
vim /etc/modprobe.d/blacklist.conf (or use nano). Comment out the lines that you added for the installation procedure (per readme file).
init 6 (to reboot)

You may go the extra mile and blacklist the driver just in case. To do that, I would assume you added the line from the modules file with 'blacklist' in front of it.

If you are trying to install this driver to solve wifi not connecting after suspend, read the solution that is in the QUESTION on the following: http://askubuntu.com/questions/452826/wireless-networking-not-working-after-resume-in-ubuntu-14-04

Hope this helps anyone in the future!

**Comment by Syno0** [comment]
Old one, not remembering this issue to be honest.
