### ISSUE TITLE
Compile error "cp: cannot create regular file '/tftpboot': Permission denied"

### ISSUE THREAD

**Issue by pedronf65** [agerwick/RT28XX-RT539X-Linux-driver#3]
I'm having this compile error after doing make:
cp: cannot create regular file '/tftpboot': Permission denied
I'm compiling this in arch linux, in Makefile:
PLATFORM = PC
I'm compiling with a normal user, of course.
It looks like make is copying a file into /tftpboot folder, is it normal? Looking inside Makefile I see it in lots of places... I don't have this folder in my file system.
So, two questions:
1. why make is copying files? They should be copied only with make install
2. why is it using this folder named /tftpboot ?

**Comment by agerwick** [comment]
This is now old, and I can't reproduce due to no longer having the wireless card in question. Also, this solution was made for Ubuntu, so YMMV on other distributions.
