### ISSUE TITLE
depmod: ERROR: Bad version passed rt5390sta

### ISSUE THREAD

**Issue by pedronf65** [agerwick/RT28XX-RT539X-Linux-driver#4]
After creating the missing folder from the previous issue I managed to compile and install the driver.
But now I have another issue:
$ sudo depmod rt5390sta
depmod: ERROR: Bad version passed rt5390sta

$ modinfo rt5390sta
filename:       /lib/modules/4.4.2-2-rt7-ARCH/kernel/drivers/net/wireless/rt5390sta.ko
version:        2.6.0.0
srcversion:     95F69F45628F41F1E10506E
alias:          pci:v00001186d00003C05sv_sd_bc_sc_i*
alias:          pci:v00001814d00005362sv_sd_bc_sc_i*
alias:          pci:v00001814d00005392sv_sd_bc_sc_i*
alias:          pci:v00001814d0000539Fsv_sd_bc_sc_i*
alias:          pci:v00001814d00005390sv_sd_bc_sc_i*
alias:          pci:v00001814d00003390sv_sd_bc_sc_i*
alias:          pci:v00001814d00003092sv_sd_bc_sc_i*
alias:          pci:v00001814d00003091sv_sd_bc_sc_i*
alias:          pci:v00001814d00003090sv_sd_bc_sc_i*
depends:
vermagic:       4.4.2-2-rt7-ARCH SMP preempt mod_unload modversions ARMv7 p2v8
parm:           mac:rt28xx: wireless mac addr (charp)

$ uname -a
Linux udoo-quad 4.4.2-2-rt7-ARCH #1 SMP PREEMPT RT Fri Feb 26 00:58:50 UTC 2016 armv7l GNU/Linux

My gcc version:
gcc version 5.3.0 (GCC)

**Comment by cyates559** [comment]
It looks like I'm having the same exact problem.  Any solution?

**Comment by agerwick** [comment]
I fixed an issue (#6) showing up on Ubuntu 16.04 related to the version number, but I'm not sure if it's related. If you're making this work on Arch Linux or other distributions and have modifications needed to make it work, I suggest forking, then making a pull request. If someone can test your solution on Ubuntu and that works, then I'll merge it.
