### ISSUE TITLE
It just doesn't work on my laptop

### ISSUE THREAD

**Issue by memeheck** [agerwick/RT28XX-RT539X-Linux-driver#5]
Running Ubuntu 14.04LTS on an HP 2000-bl69wh, and it just doesn't work at all. Still sitting on my LAN network, would prefer to be WAN for portability.

**Comment by agerwick** [comment]
Your laptop seems to have the RT5390 from what I can find on the net, but there's just not enough info in this issue report to provide any assistance.

**Comment by ylab324** [comment]
hello

at the beginning, rt2800pci worked on my hp laptop , wifi ran slowly ,but at least it worked

and then i installed rt5390sta as README saying just now，no errors reported，it seems that everything's ok ,but after i rebooted my laptop, i could not find wifi on my network manager

i run " lsmod | grep rt5390sta " on terminal,  get "rt5390sta            1433600  0"

and lspci -v
        Network controller: Ralink corp. RT5390 Wireless 802.11n 1T/1R PCIe
	Subsystem: Hewlett-Packard Company U98Z077.00 Half-size Mini PCIe Card
	Flags: bus master, fast devsel, latency 0, IRQ 16
	Memory at d3500000 (32-bit, non-prefetchable) [size=64K]
	Capabilities: <access denied>
	Kernel driver in use: rt2860
	Kernel modules: rt2800pci, rt5390sta

what's wrong with it ?
